=== KritzHeng/public-schema/attestation/attestation.schema.json
{
  "$id": "ED9ta8o1xTm3LR9apIj6ImS1wQEOcEUmMd19aUa7tjDL",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Data Attestation Credential",
  "description": "Data attestation credential enables verifiable attestation of the data(cryptographic digest) by the Issuer",
  "type": "object",
  "credentialType": "DataAttestationCredential",
  "version": "1.0.0",
  "properties": {
    "v": {
      "description": "Version",
      "type": "string"
    },
    "d": {
      "description": "Credential SAID",
      "type": "string"
    },
    "i": {
      "description": "Issuer AID",
      "type": "string"
    },
    "ri": {
      "description": "Credential status registry",
      "type": "string"
    },
    "s": {
      "description": "schema SAID",
      "type": "string"
    },
    "a": {
      "$id": "EPd8VTJOJ6S1rDQzQWE9nWSCFCJwiNSqTWHaTELZDAON",
      "description": "Attributes block",
      "type": "object",
      "properties": {
        "d": {
          "description": "Attributes block SAID",
          "type": "string"
        },
        "dt": {
          "description": "Issuance date time",
          "format": "date-time",
          "type": "string"
        },
        "xsaid": {
          "type": "string",
          "description": "CESR-encoded digest of the data."
        }
      },
      "additionalProperties": false,
      "required": [
        "d",
        "dt",
        "xsaid"
      ]
    },
    "e": {
      "oneOf": [
        {
          "$id": "EGdpNTt_v5NAIhzWZjisHE5oaYnoJVOC7iVFySw9eFKX",
          "description": "Chained vLEI OOR Credential",
          "properties": {
            "d": {
              "description": "SAID of edge block containing OOR Credential node",
              "type": "string"
            },
            "oor": {
              "description": "node SAID of signer OOR credential",
              "properties": {
                "n": {
                  "type": "string"
                },
                "s": {
                  "type": "string",
                  "description": "SAID of required schema of the credential pointed to by this node",
                  "const": "EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s"
              ],
              "type": "object"
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "oor"
          ],
          "type": "object"
        },
        {
          "$id": "EO2AOkCvsjm5RyQYAPpUZP96pbXlPGym57VemjxlOlMe",
          "description": "Chained vLEI ECR Credential",
          "properties": {
            "d": {
              "description": "SAID of edge block contai0ning ECR Credential node",
              "type": "string"
            },
            "ecr": {
              "description": "node SAID of signer ECR credential",
              "properties": {
                "n": {
                  "type": "string"
                },
                "s": {
                  "type": "string",
                  "description": "SAID of required schema of the credential pointed to by this node",
                  "const": "EEy9PkikFcANV1l7EHukCeXqrzT1hNZjGlUk7wuMO5jw"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s"
              ],
              "type": "object"
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "ecr"
          ],
          "type": "object"
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "ri",
    "s",
    "d"
  ]
}

=== KritzHeng/public-schema/attestation/example-attestation.json
{
  "v": "ACDC10JSON000177_",
  "d": "EBM2Z3aQrsx1FYEH4wkrZarMUGysUWIGFGb0dBffBL17",
  "i": "EIw_fe9e7TTGUL5nrXfjuzqzGWq7iHc4mzmGiqb_CCGK",
  "ri": "EAEBPOD8GzIYVKlElExZroScFvGbiKdLjbcJ4XuYeOQv",
  "s": "ED9ta8o1xTm3LR9apIj6ImS1wQEOcEUmMd19aUa7tjDL",
  "a": {
    "d": "EHfPLy-fEuPe3Ug9f8ZE2LTrzfcvF0pwnCV6UJK_ApoV",
    "dt": "2024-11-01T14:23:16+00:00",
    "xsaid": "EGvjHeAo7ZRQYUCb3Xh9TBdLhoMuW4lBSmOeR6gkMhMg"
  }
}
